### ISSUE TITLE
Meteor settings public is undefined

### ISSUE THREAD

**Issue by Flowtter** [l3mpire/lemverse#131]
We noticed that under a lot of stress on the CPU, users could not connect anymore.
In the function `restrictedRegistration` of the file `form-account.js`, the variable `const { permissions } = Meteor.settings.public;` is undefined.
The function then tries to access the field `allowAccountCreation`, crashes and the user can't connect since it `cannot read property 'allowAccountCreation' of undefined`.

**Comment by ramnes** [comment]
For now we're digging for the root cause but we'll provide step-by-step instructions if we can't fix it by ourselves. :)

**Comment by ramnes** [comment]
Closing as we're most likely not going to fix this independently. It's a side effect of a more general problem (namely #80).
