### ISSUE TITLE
Play random punch sounds

### ISSUE THREAD

**Issue by Raamyy** [l3mpire/lemverse#167]
We can add more punch sounds and When `X` is pressed, a random sound is picked and played.

This is inspired by the hidden _HADOUKEN_ sound in the assets 😆

**Comment by Raamyy** [comment]
@ramnes Can you advice where to get another punch sounds?

I read that you use Itch.io assets, Am I free to pick from them?

**Comment by ramnes** [comment]
No idea where the current punch sounds come from, maybe @Donorhan knows?

**Comment by Donorhan** [comment]
I didn't develop the punch so I don't have the origin of the sound but I think it comes from [freesound.org](https://freesound.org/search/?q=punch). This is a good website to get royalty free sounds 🙂.

A technique very often used in games is to keep the same sound but play it with different audio pitch in a random way, an article about this [exists here](https://www.reddit.com/r/gamedev/comments/5mn4yg/the_power_of_pitch_shifting/), I did not look if it is possible to play it natively in Javascript.
