### ISSUE TITLE
How to activate the custom oauth login button?

### ISSUE THREAD

**Issue by thomasfaure** [l3mpire/lemverse#204]
Hello, I configured the settings.json with a custom authentication button, but it has no effect. How to activate this configuration?

**Comment by ramnes** [comment]
It has been implemented in #46 and #47, so it might be worth summoning @alizarion – can you help?

**Comment by alizarion** [comment]
hi @thomasfaure, which lemverse release are you using? I just tested with the latest on docker hub and it seems to work
can you give us more details?
does the buttons appear on the login section?
![Capture d’écran 2022-11-14 à 13 20 44](https://user-images.githubusercontent.com/4605295/201659658-84430ccf-8c69-4401-bcab-02f0b6ef43ac.png)

**Comment by thomasfaure** [comment]
I deployed the master version (1b11733ba888b5905b724241ff6a73c3f104a2bb), but I don't see the custom buttons which are well configured in the settings file

**Comment by alizarion** [comment]
can you share your configuration? buttons can be hidden can you try to add  "hidden": false

**Comment by thomasfaure** [comment]
Yes, here is an extract of the configuration:

`"packages": {
      "service-configuration": {
        "custom": {
          "buttonBackgroundColor": "#ea4335",
          "buttonTextColor": "white",
          "clientId": "lemverse",
          "type": "oauth",
          "custom": true,
          "hidden": false,
          "secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "authUrl": "https://my.whaller.com/oauth2/authorize",
          "accessTokenUrl": "https://my.whaller.com/api/oauth2/access_token",
          "identityUrl": "https://my.whaller.com/api/person/me",
          "serverURL": "https://xxxxxx.whaller.com",
          "responseType": "code",
          "loginStyle": "redirect",
          "scope": "openid",
          "identity": ["sname", "fname"]
        },
        "twitter": {
          "consumerKey": "xxxxxxx",
          "secret": "xxxxxxx",
          "type": "oauth",
          "custom": false,
          "loginStyle": "redirect"
        },
        "github": {
          "clientId": "xxxxxxx",
          "buttonBackgroundColor": "#5880ff",
          "buttonTextColor": "white",
          "type": "oauth",
          "custom": false,
          "secret": "xxxxxxx"
        },
        "google": {
          "clientId": "xxxxxxx",
          "buttonBackgroundColor": "#5880ff",
          "buttonTextColor": "white",
          "type": "oauth",
          "custom": false,
          "secret": "xxxxxxx",
          "loginStyle": "redirect"
        },
        "facebook": {
          "appId": "xxxxxxx",
          "buttonBackgroundColor": "#5880ff",
          "buttonTextColor": "white",
          "type": "oauth",
          "custom": false,
          "secret": "xxxxxxx",
          "loginStyle": "redirect"
        }
      },`

**Comment by alizarion** [comment]
@thomasfaure sorry for late answer, it's your own build or official lemverse docker image ?
i think your configuration file or env is not parsed correctly ...
can you try this in chrome console

      ServiceConfiguration.configurations.find()
		      .observe({
			      added(record) {
				      console.log(record);
				      
			      },
		      });

**Comment by thomasfaure** [comment]
@alizarion 

Here is the screenshot of the answer, I don't know if it can help.

![image](https://user-images.githubusercontent.com/4790431/203025532-8dc9a2ed-d200-40af-bc5f-0b44edc832f6.png)

**Comment by alizarion** [comment]
@thomasfaure I think the second line of the query is ignored because of the copy paste :) 
you should see something like this
![Capture d’écran 2022-11-21 à 11 28 08](https://user-images.githubusercontent.com/4605295/203027594-2a4ffb6a-f811-40e3-8955-fbc5070308be.png)

**Comment by alizarion** [comment]
if no records it means your configuration is ignored

**Comment by thomasfaure** [comment]
yes, which makes sense since I don't see a custom button. 

Do you know why it is ignored? 

Two things: 

the "packages" scope is not in "public" : 

![image](https://user-images.githubusercontent.com/4790431/203033295-457e39d4-a620-4f65-81c4-54d0b81e6028.png)

and the "packages" scope is inside a "peer" scope: 

![image](https://user-images.githubusercontent.com/4790431/203033250-6a288e90-7fb9-4e6f-90c8-12ade64d2f3c.png)

**Comment by thomasfaure** [comment]
@alizarion it's better now :) 

![image](https://user-images.githubusercontent.com/4790431/203038061-4ff1d650-9215-414a-8bd1-f28b211bfa64.png)
