### ISSUE TITLE
Zone over zone don't work anymore

### ISSUE THREAD

**Issue by riderx** [l3mpire/lemverse#31]
Define a big zone and tiny one inside the big one like the picture :
<img width="321" alt="Screenshot 2021-10-05 at 11 51 57" src="https://user-images.githubusercontent.com/4084527/136009738-e677d906-6d66-48bd-b131-0b176a3b346a.png">
try to walk on the big one, you enter in it, try the tiny one, it's doesn't work.
it was working before and very useful to show info to user when they are in a zone

**Comment by Donorhan** [comment]
I just tried on master I don't have the problem. Did you do anything in particular?
<img width="469" alt="Capture d’écran, le 2021-10-05 à 14 14 27" src="https://user-images.githubusercontent.com/3781087/136020262-c24db94f-78f7-4810-b5d6-54d932084dff.png">
<img width="666" alt="Capture d’écran, le 2021-10-05 à 14 14 51" src="https://user-images.githubusercontent.com/3781087/136020319-09e445ed-ea33-4de5-a076-342db1afec14.png">

**Comment by riderx** [comment]
@Donorhan 
here is my tiny zone for my pannel it uses inline URL:
```
{
  "levelId": "lvl_iRaqGsbWMcMTdoBZj",
  "adminOnly": "",
  "fullscreen": false,
  "inlineURL": "<h1>INDIE VERSE Rules</h1><p>don't disturb people in calling zone</p><p>If someone has mic cut, it means he work on something, don't blame him if he doesn't respond straight.</p><p>Take a sit do your work</p><p>you can use meeting room if they are empty.</p><p>If you want to do a conference, contact Martin to book the conference room</p><p>You can play board game in the gaming room</p><p> You can create your own wolrd if you found the teleporter</p><p><b>Tonight at 6PM Paris UTC+2 Come to chill zone to have a drink</b></p>",
  "name": "",
  "roomName": "",
  "targetedLevelId": "",
  "teleportEndpoint": "",
  "unhide": "",
  "unmute": "",
  "url": "",
  "popInConfiguration": {
    "width": 320,
    "height": 560
  }
}
```
and the big one have just name:
```
{
  "levelId": "lvl_iRaqGsbWMcMTdoBZj",
  "adminOnly": "",
  "fullscreen": false,
  "inlineURL": "",
  "name": "Open space",
  "roomName": "",
  "targetedLevelId": "",
  "teleportEndpoint": "",
  "unhide": "",
  "unmute": "",
  "url": ""
}
```

**Comment by Donorhan** [comment]
Currently the zone detection depends on its creation order, I will apply a first fix but I'll have to work on a more elegant one later.

**Comment by Donorhan** [comment]
Fixed in [this commit](https://github.com/l3mpire/lemverse/commit/d36187c91c92f5cfa8626d365106c55e8c173d17)
