### ISSUE TITLE
As Editor you don't know tile props

### ISSUE THREAD

**Issue by riderx** [l3mpire/lemverse#33]
When hover a tile in the editor selection area we don't know if the tile has collision or in witch level it will be set .
<img width="1029" alt="Screenshot 2021-10-30 at 13 51 23" src="https://user-images.githubusercontent.com/4084527/139533507-93689b58-66c7-48b5-a037-375c1224dbd8.png">

For people who just start to learn it's difficult

**Comment by DblK** [comment]
I do not see the point of knowing in which level it will be set. I will be added in the current level.
Talking about collision, it's all explain in the readme.
At some point, we will merge the current editor with the route `/editor`; doing so, you will be able to add tileset and edit collision in the same window.

**Comment by DblK** [comment]
okay. So for collision, once placed on the screen, the user will know if it has collision or not.
It's the admin role to setup everything right (collisions, layer, etc...).

As for layer, the user should only place them. Same as collision if the admin has done its job it should be okay. If not, user can tell the admin to fix it.

If the user has done something bad, there is still the `cmd+z` shortcut to undo things.

**Comment by riderx** [comment]
@DblK i agree user can place on the screen to see if that hae collision or not, but you cannot say it's user friendly.

I agree the role of the admin is to setup everything good,
We let `editor` select the tile level when they erase tile,
it sound weird to don't let `editor` know in wich level they will set the tile.

Please put yourself in the `editor` shoes, i got the feedback 5 time already, they don't understand where they put tile, and what tile have colission.

The number and the collision color on tile in the editor page are perfect for this.
they just need it in `editor` interface.

**Comment by DblK** [comment]
![lemverse-editor](https://user-images.githubusercontent.com/832617/140526231-9a46e00e-f997-4635-bf9c-b87dfae03ceb.png)

As for editor, except collision (which should be obvious based on the tile), you already have the current layer `selected` and also on the tile, the list of existing tiles with their corresponding layers.

Am I missing something?

**Comment by riderx** [comment]
@DblK you are right, i never saw `selected` exist.
I think that make the point more valuable, even power user miss it.

i will try to propose a new design to improve it.
For collision, i still think explicit will be better than implicit behavior.
