### ISSUE TITLE
Be able to manage access to areas on app.lemverse.com

### ISSUE THREAD

**Issue by apinto2-scc** [l3mpire/lemverse#37]
Hello,

Thank you for your work the idea is really top! I am a fan. 💛💛💛

I was wondering if it is planned to have the ability to manage access to zones directly on https://app.lemverse.com/ without necessarily having to mount its own instance, for example with a list of user id or emails are allowed to enter the zone.

Have a nice day.

**Comment by DblK** [comment]
Hi,
Thanks for your message.
For now, as per documentation, there is only a way to have admin zones which can be done only in your own instance.

We might be able to extend it, but could you tell me more about your use case? Maybe with the name of your own level or a link to it (via `Settings`->`Copy invitation link`)

**Comment by apinto2-scc** [comment]
My use case is the following:

I would like to create a universe that represents my company, with a zone that would be a showroom, where we could also do public talks. And a space reserved for the employees of my company where only they can access.


Other :
We want to promote gamification in our company and through your product, I see a direct lever to propose it to employees.
Is your product intended to be a SAAS platform? Where I set up my universe but I can also have metrics of usage by users?


Invite: app.lemverse.com/invite/C3dkJSKDHGL8CrRCi

**Comment by YglesEyes** [comment]
Closed because already implemented by Editor => Zones => accessRestrictedToGuild
