### ISSUE TITLE
Multiple scripts doesn't seem to work?

### ISSUE THREAD

**Issue by mikeslaatsio** [l3mpire/lemverse#38]
Helpful video explaining and showing the issues: https://www.loom.com/share/649cf8d99260409a87226ba9c17379cc

I tried adding the same script to multiple/different zones. In the first zone, it works perfectly, all the other/new ones, it doesn't. Also, can you please provide me with a script for the pop-up message, I tried this one:

`{
  "adminOnly": "",
  "disableCommunications": false,
  "fullscreen": false,
  "hideName": false,
  "inlineURL": "<h1>LUNCH ROOM</h1><p>Please, don't disturb people when eating their lunch.</p>",
  "name": "Lunch Room Notice 1",
  "roomName": "",
  "targetedLevelId": "",
  "teleportEndpoint": "",
  "unhide": "",
  "unmute": "",
  "popInConfiguration": {
    "width": 320,
    "height": 560
  },
  "url": ""
}`

But doesn't seem to do anything.

Thanks!

Mike

**Comment by Donorhan** [comment]
Hi Mike, I just saw your email and tested in your level.

I'm not sure why yet but the coordinates of your zones were not correct, I drew the start and end position of your zones again and everything works now.

I also added a demo pop-in to show you how it works at the entrance of your level :)

**Comment by mikeslaatsio** [comment]
Thanks for your help! Worked for one new pop up, but soon after that it stopped working already :( Am I doing something wrong? Here's how I create zones: https://www.loom.com/share/73c21ca605fa4d21b9beb5f085f74141

PS also struggling with the teleporter zone

**Comment by mikeslaatsio** [comment]
Thank you so much! We're almost there.. only thing I'm struggling with is creating a teleporter to another level/world. When I do this:

`{
  "adminOnly": "",
  "disableCommunications": false,
  "fullscreen": false,
  "hideName": false,
  "inlineURL": "",
  "name": "Upvoty HQ Teleporter",
  "roomName": "Upvoty HQ",
  "targetedLevelId": "oJJMbaKzoCzmr8LAe",
  "teleportEndpoint": "",
  "unhide": "",
  "unmute": "",
  "url": ""
}`

You'll be sent to the main lobby and not to that exact world (https://app.lemverse.com/invite/oJJMbaKzoCzmr8LAe)

**Comment by Donorhan** [comment]
You are missing "lvl_" in front of the target level id:
`"targetedLevelId": "lvl_oJJMbaKzoCzmr8LAe"`

**Comment by mikeslaatsio** [comment]
Something really strange is happening if I do that.. https://www.loom.com/share/25c1cf0ce3df4b74ad8062f4e0e3067d (it's opening up the meeting room?)

**Comment by mikeslaatsio** [comment]
Tried in in a different place, nothing happens? https://www.loom.com/share/fe63779786fb46cfb2ec5925dc067e2b

**Comment by Donorhan** [comment]
Currently teleporters to the current level are not allowed.

For the first problem, you have to remove the "roomName" attribute or leave it empty, this attribute opens a Jitsi.

**Comment by mikeslaatsio** [comment]
All good now! I actually used the wrong level id haha lol. Thanks for all your help!

**Comment by mikeslaatsio** [comment]
PS: We've created a feedback portal where we'll gather feedback about Lemverse: https://lemverse.upvoty.com/b/feedback/. We even embedded this in our lobby: https://www.loom.com/share/fab15c723183447b98c25dc95893aa6e

Hopefully, we can get some nice feedback to improve the software. Feel free to embed it in your world as well, or maybe in the main lobby so other users can join and participate. If you want to become an admin of this portal, shoot me a message :)

**Comment by mikeslaatsio** [comment]
People are leaving their feedback, there's some awesome stuff in it already, check: https://lemverse.upvoty.com/b/feedback/. Follow-mode is something that would be very useful! :)

**Comment by DblK** [comment]
Duplicate see #31
