### ISSUE TITLE
Contact popup displayed on click share-screen

### ISSUE THREAD

**Issue by DblK** [l3mpire/lemverse#39]
When you are viewing the screen of someone in full screen, to reduce it you need to click again on it.
However, if there is someone under the fullscreen view, it will trigger the contact popup display.

We should not bubble event on click.

**Comment by Donorhan** [comment]
fix in [#disable phaser mouse events when an interface is open](https://github.com/l3mpire/lemverse/commit/05798942d65c65e097ab90368c02d36e83793864)
