### ISSUE TITLE
Docker settings error

### ISSUE THREAD

**Issue by freddy-wtf** [l3mpire/lemverse#44]
I have a problem with the new release.

`2021-12-14T12:05:18.222634679Z Meteor.settings: lemverse.json cannot read file _FID0 {"err":{"errno":-2,"syscall":"open","code":"ENOENT","path":"/usr/local/etc/lemverse.json"}} Error: ENOENT: no such file or directory, open '/usr/local/etc/lemverse.json' Error: ENOENT: no such file or directory, open '/usr/local/etc/lemverse.json'`

**Comment by DblK** [comment]
To let other knows, this log is not blocking for the launch of the app.
As stated in the readme, it's used serverside only to store your secret.
