### ISSUE TITLE
Keep filenames when uploading tilesets

### ISSUE THREAD

**Issue by ramnes** [l3mpire/lemverse#58]
When uploading tilesets, they get names such as `tis_ox8ux7ntwhReEPknW`. Renaming all tilesets is a pain, let's keep the original filenames instead, they are more likely to mean something.

**Comment by Donorhan** [comment]
We preserve the name at the upload, we rely on the name to know if a tileset is already uploaded or not (the fileName attribute)

<img width="355" alt="Capture d’écran, le 2022-07-15 à 09 13 34" src="https://user-images.githubusercontent.com/3781087/179171725-b0072eef-ee79-458c-a59e-854d95604693.png">

**Comment by Donorhan** [comment]
I had misunderstood, indeed we can use `fileName`, it will be easier to find the last uploaded file 🙂
