### ISSUE TITLE
Support animated assets

### ISSUE THREAD

**Issue by ramnes** [l3mpire/lemverse#59]
LimeZu makes nice GIF assets, that would be great if we could add them to the editor somehow!

**Comment by Donorhan** [comment]
Phaser doesn't support gif, the best is to be able to import sprite sheets and to have a customizable animation/state system. This is what I started to do with the entity system which is independent from the tilemap

**Comment by Donorhan** [comment]
This is now possible with entities, I have put some documentation about this in the [Readme](https://github.com/l3mpire/lemverse#entity-edit)
