### ISSUE TITLE
Detect device change during a chat

### ISSUE THREAD

**Issue by Donorhan** [l3mpire/lemverse#67]
## What is the current behavior?
When you talk to someone and connect a new device like a headset the stream sent to the remote user is not updated

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
- Talk to someone
- Connect another device like a headset
- The other can't hear you anymore

## What is the expected behavior?
The remote user should always hear the user who has connected a headset

## What is the motivation / use case for changing the behavior?
Allow users to communicate seamlessly

## Please tell us about your environment:

Platform: Web & Desktop
Browser: Chrome 103
Language: FR

**Comment by YglesEyes** [comment]
navigator.mediaDevice.ondevicechange is not triggered when a bluetooth device is connected/disconnected.
