### ISSUE TITLE
Being god to use /editor

### ISSUE THREAD

**Issue by romainvalluy** [l3mpire/lemverse#70]
Prod deployement : I am a god in the settings.json. 
I get "Error while changing category, only gods can do this" as I try to qualify  Hair styles in the character editor (/editor).
I can use the other functions with the tilsets (wall, floor, setting as wall or collision zone etc.)

**Comment by Donorhan** [comment]
Have you tried to restart your instance after the settings file has been modified? Are you sure your user_id is the right one in the settings file?

**Comment by romainvalluy** [comment]
Use the last version of lemverse.
I did :
docker restart
 docker image / volume/ container (of lemverse)  rm 

checked that it is my good user ID in the good settings.json

before writting here ;-)

And i got this message about being god to be allowed to use the character editor, althought i am an editor too.

**Comment by romainvalluy** [comment]
the active settings where in the docker file...  ;-)  Now its fixed!
