### ISSUE TITLE
Implement zoom on mobile

### ISSUE THREAD

**Issue by ramnes** [l3mpire/lemverse#77]
It's currently impossible to zoom on mobile (or, for our purposes, to dezoom). "Pinch to zoom" or a zoom slider would be two great features.

**Comment by Donorhan** [comment]
It seems to me that this is related to the fact that Phaser doesn't handle pinch very well and that on the Mac pinch applies an operating system zoom rather than a camera zoom

**Comment by ramnes** [comment]
I'm sure we can still find something to implement for mobile users!

**Comment by alimtunc** [comment]
I've just found a plugin that could help for the pinch zoom made by rexrainbow : https://phaser.discourse.group/t/using-multitouch-for-pinch-to-zoom/243/2

But I don't see any plugin implementation like this in the project : https://rexrainbow.github.io/phaser3-rex-notes/docs/site/gesture-pinch/?h=pinch

Is it a bad practice or a personal choice or just maybe never needed using an external plugin in the project @Donorhan ? 
I'm not familiar with phaser, I prefer to ask before trying to using it :)

**Comment by Donorhan** [comment]
This plugin sounds great to me. We never needed plugins until now that's why we don't use them currently 🙂
