### ISSUE TITLE
Everyone spawns at the same place

### ISSUE THREAD

**Issue by ramnes** [l3mpire/lemverse#78]
When a lot of people are joining a level at the same time, it's quite disturbing that everyone spawns at the same place. That's especially true for newcomers: they arrive in a very crowded place, sometimes without even seeing their own character, and that doesn't help when they have to figure out what to do.

I see two ways of avoiding this issue. The first one would be to simply add a radius and jitter option around the spawn position. The second one, which I feel is more interesting, would be to add a spawn option to zones. Users would then spawn in a random position within the spawn zones, or in the default spawn position if no such zone exist.

**Comment by Donorhan** [comment]
I really like the idea of spawn zones, it would allow to define one or more zones and several positions in this zone  👍🏻

The idea would be to create an attribute on a zone to indicate that it is a spawn zone. Then at the spawn, if a spawn zone exists use it, otherwise use the attribute "spawnPosition" of the level while waiting for a futur migration.

**Comment by Donorhan** [comment]
Added in the commit https://github.com/l3mpire/lemverse/commit/ec36e81c9c030ac6247fb933152ec1adf628d581. It is also possible to define several spawn zones 🙂

**Comment by alimtunc** [comment]
> Added in the commit [ec36e81](https://github.com/l3mpire/lemverse/commit/ec36e81c9c030ac6247fb933152ec1adf628d581). It is also possible to define several spawn zones 🙂

I've just started to look on this today, aha nice if you did it faster, gj 💯

**Comment by Donorhan** [comment]
Damn I should have tagged myself on the issue, sorry!

**Comment by ramnes** [comment]
Very nice, thanks @Donorhan!

IMHO `Math.random()` is perfect for this kind of use case, we have no need for a high level of entropy.

Let's talk on Discord as to how we can collaborate better, e.g. so that we don't work simultaneously on something. :P
