### ISSUE TITLE
Broken UI on mobile

### ISSUE THREAD

**Issue by ramnes** [l3mpire/lemverse#91]
I was trying to logout, but it seems that most of these buttons simply do not work on mobile:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/835072/187457748-b4c15608-bd7f-4ee4-b9fa-4f4cf0bc71ff.png">

**Comment by Donorhan** [comment]
It should be fine now 🙂

**Comment by ramnes** [comment]
Yes it is, but then #98 :D
