### ISSUE TITLE
Uncentered communication circle

### ISSUE THREAD

**Issue by ramnes** [l3mpire/lemverse#96]
When a user dezooms, at some point communication circles are off:

From Louis' perspective:
![image](https://user-images.githubusercontent.com/835072/187651690-3db17441-82db-445f-ac53-23e03f1bdff6.png)

From Guillaume's perspective:
![image](https://user-images.githubusercontent.com/835072/187651712-11796fa4-4b4d-493b-bf16-5155e8c05116.png)

**Comment by Donorhan** [comment]
I can take care of it, I was planning to redo this circle management logic and eventually improve it visually

**Comment by ramnes** [comment]
awesome :)
