### ISSUE TITLE
UI isn't responsive

### ISSUE THREAD

**Issue by ramnes** [l3mpire/lemverse#98]
![Screenshot_20220901-122058](https://user-images.githubusercontent.com/835072/187894268-88d217b7-e69c-449c-9dc2-5fa046872858.jpg)
![Screenshot_20220901-122757](https://user-images.githubusercontent.com/835072/187894273-e0b2d454-2f70-47eb-9df4-b9be0578b806.jpg)
![Screenshot_20220901-122804](https://user-images.githubusercontent.com/835072/187894275-adc7b65c-11ee-4556-8419-828e02aa6edf.jpg)

**Comment by YglesEyes** [comment]
https://user-images.githubusercontent.com/1770341/189920229-d2d16d36-770c-4984-9d1f-41c78e4acc6c.mp4
